# -*- coding: utf-8 -*-
"""220 lab 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jse8IWajVXN2qqPpVqC1QJinD2IA8Zfg

**Shift left K cells**
"""

source=[10,20,30,40,50,60]
shift= 3
def shiftLeft(array,k):
  for i in range (0,shift):
    for j in range (0, len(array)-1):
      array[j]=array[j+1]
    array[len(array)-1]=0

  for i in range(0 , len(array)):
    print(array[i])

shiftLeft(source,shift)

"""**Rotate left K cells**"""

source=[10,20,30,40,50,60]
shift= 3
def rotateLeft(array,k):
  for i in range (0,shift):
    temp= array[0] 
    for j in range (0, len(array)-1):
      array[j]=array[j+1]
    array[len(array)-1]= temp

  for i in range(0 , len(array)):
    print(array[i])

rotateLeft(source,shift)

"""**Remove an element from an array**"""

source=[10,20,30,40,50,0,0]
def removeElement(array,size,k):
  #for i in range(0,len(array)-1):
    array[k]= 0
    for j in range(k,len(array)-1):
       array[j]= array[j+1]

    array[len(array)-1]=0

    for i in range(0 , len(array)):
       print(array[i])

removeElement(source,5,2)

"""**Remove all occurences of an element from an array**"""

source =[10,2,30,2,50,2,2,0,0]
def removeAll(array,size,k):
  for i in range(0,len(array)-1):
    if array[i]==k :
      array[i]= 0
      for j in range(i,len(array)-1):
       array[j]= array[j+1]
    array[len(array)-1]=0
    if array[i-1]==k:
      array[i-1]==0
      for j in range(i-1,len(array)-1):
        array[j]=array[j+1]
      array[len(array)-1]=0


  for i in range(0 , len(array)):
       print(array[i])

removeAll(source,7,2)

"""**Splitting an array**"""

def splitArray(s):
  lsum=0
  rsum=0
  for i in range(0,int(len(s)/2)+1):
    l=s[i]
    lsum=lsum+l
  for j in range( len(s)-1, int(len(s)/2),-1 ):
    r=s[j]
    rsum=rsum+ r
  if lsum==rsum :
    print("True")
  else:
    print("False")

source=[2,1,1,2,1]
splitArray(source)

source=[1,1,1,2,1]
splitArray(source)

"""**Max Bunch Count**"""

def maxBunch(s):
  bcount=1
  mcount=0
  for i in range(0,bcount):
    for i in range(1,len(s)-1):
        if s[i]==s[i+1]:
          mcount=mcount + 1
    if mcount>bcount:
      bcount=mcount
          
    print(bcount)

array=[1,1,2,2,1,1,1,1]
maxBunch(array)

array=[1,2,2,3,4,4,4]
maxBunch(array)

"""**Repetition**"""

def repElement(s,c):
  
  for i in range(0,len(s)):
      no =s[i]
      c[no]=c[no]+1
  for i in range(0,len(c)-1):
     print(c[i]) #print the array that contains the number of repetitions
  if c[i]!=0 and c[i]!=1 and c[i]==c[i+1]:
    print("True")

  else:
    print("False")

a= [3,4,6,3,4,7,4,6,8,6,6]
c=[0,0,0,0,0,0,0,0,0,0,0]
repElement(a,c)

a= [4,5,6,6,4,3,6,4]
c=[0,0,0,0,0,0,0,0]
repElement(a,c)

"""**Palindrome**"""

arr=[20,10,0,0,0,10,20,30]
st=5
size=5
for i in range(st,len(arr)):
   if arr[i]==arr[(st+size-1)%len(arr)]:
      print("Pali")
   else:
      print("not")
   i=(i+1)%len(arr)
   if i<0:
      index=len(arr)-1